//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Consumo.WCF_BD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_BD.IBD")]
    public interface IBD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/CrearDTParametros", ReplyAction="http://tempuri.org/IBD/CrearDTParametrosResponse")]
        System.Data.DataTable CrearDTParametros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/CrearDTParametros", ReplyAction="http://tempuri.org/IBD/CrearDTParametrosResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> CrearDTParametrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarFiltrarDatos", ReplyAction="http://tempuri.org/IBD/ListarFiltrarDatosResponse")]
        Web_Consumo.WCF_BD.ListarFiltrarDatosResponse ListarFiltrarDatos(Web_Consumo.WCF_BD.ListarFiltrarDatosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/ListarFiltrarDatos", ReplyAction="http://tempuri.org/IBD/ListarFiltrarDatosResponse")]
        System.Threading.Tasks.Task<Web_Consumo.WCF_BD.ListarFiltrarDatosResponse> ListarFiltrarDatosAsync(Web_Consumo.WCF_BD.ListarFiltrarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Ins_Mod_Eli_Datos", ReplyAction="http://tempuri.org/IBD/Ins_Mod_Eli_DatosResponse")]
        Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosResponse Ins_Mod_Eli_Datos(Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBD/Ins_Mod_Eli_Datos", ReplyAction="http://tempuri.org/IBD/Ins_Mod_Eli_DatosResponse")]
        System.Threading.Tasks.Task<Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosResponse> Ins_Mod_Eli_DatosAsync(Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarFiltrarDatos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarFiltrarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Data.DataTable DT_Parametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string sMsjError;
        
        public ListarFiltrarDatosRequest() {
        }
        
        public ListarFiltrarDatosRequest(string sNombreSP, System.Data.DataTable DT_Parametros, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.DT_Parametros = DT_Parametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarFiltrarDatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListarFiltrarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable ListarFiltrarDatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public ListarFiltrarDatosResponse() {
        }
        
        public ListarFiltrarDatosResponse(System.Data.DataTable ListarFiltrarDatosResult, string sMsjError) {
            this.ListarFiltrarDatosResult = ListarFiltrarDatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ins_Mod_Eli_Datos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ins_Mod_Eli_DatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sNombreSP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool bBandera;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Data.DataTable DT_Parametros;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string sMsjError;
        
        public Ins_Mod_Eli_DatosRequest() {
        }
        
        public Ins_Mod_Eli_DatosRequest(string sNombreSP, bool bBandera, System.Data.DataTable DT_Parametros, string sMsjError) {
            this.sNombreSP = sNombreSP;
            this.bBandera = bBandera;
            this.DT_Parametros = DT_Parametros;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ins_Mod_Eli_DatosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ins_Mod_Eli_DatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Ins_Mod_Eli_DatosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sMsjError;
        
        public Ins_Mod_Eli_DatosResponse() {
        }
        
        public Ins_Mod_Eli_DatosResponse(string Ins_Mod_Eli_DatosResult, string sMsjError) {
            this.Ins_Mod_Eli_DatosResult = Ins_Mod_Eli_DatosResult;
            this.sMsjError = sMsjError;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBDChannel : Web_Consumo.WCF_BD.IBD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BDClient : System.ServiceModel.ClientBase<Web_Consumo.WCF_BD.IBD>, Web_Consumo.WCF_BD.IBD {
        
        public BDClient() {
        }
        
        public BDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable CrearDTParametros() {
            return base.Channel.CrearDTParametros();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> CrearDTParametrosAsync() {
            return base.Channel.CrearDTParametrosAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Consumo.WCF_BD.ListarFiltrarDatosResponse Web_Consumo.WCF_BD.IBD.ListarFiltrarDatos(Web_Consumo.WCF_BD.ListarFiltrarDatosRequest request) {
            return base.Channel.ListarFiltrarDatos(request);
        }
        
        public System.Data.DataTable ListarFiltrarDatos(string sNombreSP, System.Data.DataTable DT_Parametros, ref string sMsjError) {
            Web_Consumo.WCF_BD.ListarFiltrarDatosRequest inValue = new Web_Consumo.WCF_BD.ListarFiltrarDatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.DT_Parametros = DT_Parametros;
            inValue.sMsjError = sMsjError;
            Web_Consumo.WCF_BD.ListarFiltrarDatosResponse retVal = ((Web_Consumo.WCF_BD.IBD)(this)).ListarFiltrarDatos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.ListarFiltrarDatosResult;
        }
        
        public System.Threading.Tasks.Task<Web_Consumo.WCF_BD.ListarFiltrarDatosResponse> ListarFiltrarDatosAsync(Web_Consumo.WCF_BD.ListarFiltrarDatosRequest request) {
            return base.Channel.ListarFiltrarDatosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosResponse Web_Consumo.WCF_BD.IBD.Ins_Mod_Eli_Datos(Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosRequest request) {
            return base.Channel.Ins_Mod_Eli_Datos(request);
        }
        
        public string Ins_Mod_Eli_Datos(string sNombreSP, bool bBandera, System.Data.DataTable DT_Parametros, ref string sMsjError) {
            Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosRequest inValue = new Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosRequest();
            inValue.sNombreSP = sNombreSP;
            inValue.bBandera = bBandera;
            inValue.DT_Parametros = DT_Parametros;
            inValue.sMsjError = sMsjError;
            Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosResponse retVal = ((Web_Consumo.WCF_BD.IBD)(this)).Ins_Mod_Eli_Datos(inValue);
            sMsjError = retVal.sMsjError;
            return retVal.Ins_Mod_Eli_DatosResult;
        }
        
        public System.Threading.Tasks.Task<Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosResponse> Ins_Mod_Eli_DatosAsync(Web_Consumo.WCF_BD.Ins_Mod_Eli_DatosRequest request) {
            return base.Channel.Ins_Mod_Eli_DatosAsync(request);
        }
    }
}
